apiVersion: apps/v1
kind: Deployment
metadata:
  name: finn-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finn-app
  template:
    metadata:
      labels:
        app: finn-app
    spec:
      containers:
      - name: finn-app
        image: arqapp/finn-app:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: finn-app-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: finn-app
  ports:
  - port: 4500
    targetPort: 80
    nodePort: 30001
